// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPKlB7kCNGfXaUvBR6USvFQUEVVIkB-HY',
    appId: '1:20251810601:web:64b435d3f9f6c7d7d7f538',
    messagingSenderId: '20251810601',
    projectId: 'encontros-7433d',
    authDomain: 'encontros-7433d.firebaseapp.com',
    storageBucket: 'encontros-7433d.firebasestorage.app',
    measurementId: 'G-JGBSN464EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXHOagG4J7zkIFZ7KKJssQCEOfZCrYuBU',
    appId: '1:20251810601:android:ec1d5b9c0387f627d7f538',
    messagingSenderId: '20251810601',
    projectId: 'encontros-7433d',
    storageBucket: 'encontros-7433d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzxhUCsJ71OXBFzkKicrPFgrZDPwxwI8U',
    appId: '1:20251810601:ios:78176967bd83a442d7f538',
    messagingSenderId: '20251810601',
    projectId: 'encontros-7433d',
    storageBucket: 'encontros-7433d.firebasestorage.app',
    iosBundleId: 'com.example.encontros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzxhUCsJ71OXBFzkKicrPFgrZDPwxwI8U',
    appId: '1:20251810601:ios:78176967bd83a442d7f538',
    messagingSenderId: '20251810601',
    projectId: 'encontros-7433d',
    storageBucket: 'encontros-7433d.firebasestorage.app',
    iosBundleId: 'com.example.encontros',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPKlB7kCNGfXaUvBR6USvFQUEVVIkB-HY',
    appId: '1:20251810601:web:896f1c89aa3f8332d7f538',
    messagingSenderId: '20251810601',
    projectId: 'encontros-7433d',
    authDomain: 'encontros-7433d.firebaseapp.com',
    storageBucket: 'encontros-7433d.firebasestorage.app',
    measurementId: 'G-W3SRX9SBH4',
  );
}